config/routes.rb
Rails.application.routes.draw do
  root 'properties#index'
  
  get 'welcome/index'
  resources :addresses do
    resources :properties 
  end

  
  resources :properties do
      resources :item_images
      resources :feedbacks
    end
    
    

  get 'admin/index'
  controller :sessions do
    get 'login'=>:new
    post 'login'=>:create
    delete 'logout'=>:destroy
  end

  get 'sessions/create'

  get 'sessions/destroy'

  resources :users
  resources :feedbacks

   namespace :api, path: '/api/1.0', format: 'json' do

       resources :properties
  end
  

  

end

app/models/property.rb
class Property < ActiveRecord::Base
  acts_as_taggable
  acts_as_taggable_on :item_types

  validates_presence_of :description, :address, :building_name, :district, :buy, :rent, :refid, :building_age, :outdoor_size, :street, :layout

  validates_uniqueness_of :refid
  
  before_create :set_uuid
  has_many :item_images 


  

  accepts_nested_attributes_for :item_images, allow_destroy: true
  def set_uuid
    self.uuid = UUIDTools::UUID.random_create.hexdigest
  end
end

app/controllers/api/properties_controller.rb
class Api::PropertiesController < ApplicationController
  layout "property",only:[:show]
  skip_before_action :authorize
  before_action :set_property, only: [:show, :edit, :update, :destroy]

  # GET /properties
  # GET /properties.json


  def index
    @properties = Property.all
  
    end

  # GET /properties/1
  # GET /properties/1.json
  def show
    respond_to do |wants|
      wants.json { render action: 'show' }
    end
  end


  # GET /properties/new
  def new

    @property = Property.new
  end

  # GET /properties/1/edit
  def edit
  end

  # POST /properties
  # POST /properties.json
  def create
    puts property_params
    @property = Property.new(property_params)

    respond_to do |format|
      if @property.save
        format.html { redirect_to @property, notice: 'Property was successfully created.' }
        format.json { render :show, status: :created, location: @property }
      else
        format.html { render :new }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /properties/1
  # PATCH/PUT /properties/1.json
  def update
    respond_to do |format|
      if @property.update(property_params)
        format.html { redirect_to @property, notice: 'Property was successfully updated.' }
        format.json { render :show, status: :ok, location: @property }
      else
        format.html { render :edit }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /properties/1
  # DELETE /properties/1.json
  def destroy
    @property.destroy
    respond_to do |format|
      format.html { redirect_to properties_url, notice: 'Property was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_property
     @property = Property.where(refid: params[:id]).first
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def property_params
      params.permit(:title, :description, :address, :bedrooms, :bathrooms, :family_rooms, :reception_rooms, :latitude, :longitude, :features, :agent_id, :agent_name, :date_available, :building_name, :district, :indoor_size, :saleable_area, :buy, :rent, :refid, :building_age, :outdoor_size, :float, :inclusive_display, :inclusive_mfee, :inclusive_govr, :address_display, :street, :view, :layout, :floor, :uuid, :enabled,:tag_list, item_images_attributes: [:refid, :image_url,:_destroy])
    end
   
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  layout "property",only:[:show]
  skip_before_action :authorize
  before_action :set_property, only: [:show, :edit, :update, :destroy]

  # GET /properties
  # GET /properties.json



  def index
    @properties= Property.where(enabled: '1').limit(98)
   end
  # GET /properties/1
  # GET /properties/1.json
  def show

    @feedback=Feedback.new
    @city=@property.city
    @address=Address.where(city: @city).first
    
   require 'uri'

   require 'net/http'
  
   @building_name2=@property.building_name
   @description2=@property.description
   @building_name =  URI.encode(@building_name2)
   @description=  URI.encode(@description2)
   uri = URI("http://openapi.baidu.com/public/2.0/bmt/translate?client_id=wczI7xUBqYDdxOWIQsnoCAi5&q=#{@building_name}%0A#{@description}&from=auto&to=auto
")

  Net::HTTP.start(uri.host, uri.port,
  :use_ssl => uri.scheme == 'https') do |http|
  request = Net::HTTP::Get.new uri
  response = http.request request
  res=JSON.parse response.body
  @building_name1=res["trans_result"][0]['dst']
  @description1=res["trans_result"][1]['dst'].html_safe

end

   
  end

  # GET /properties/new
  def new

    @property = Property.new
  end

  # GET /properties/1/edit
  def edit
  end

  # POST /properties
  # POST /properties.json
  def create
    @property = Property.new(property_params)

    respond_to do |format|
      if @property.save
        format.html { redirect_to @property, notice: 'Property was successfully created.' }
        format.json { render :show, status: :created, location: @property }
      else
        format.html { render :new }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /properties/1
  # PATCH/PUT /properties/1.json
  def update
    respond_to do |format|
      if @property.update(property_params)
        format.html { redirect_to @property, notice: 'Property was successfully updated.' }
        format.json { render :show, status: :ok, location: @property }
      else
        format.html { render :edit }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /properties/1
  # DELETE /properties/1.json
  def destroy
    @property.destroy
    respond_to do |format|
      format.html { redirect_to properties_url, notice: 'Property was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_property
     @property = Property.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def property_params
      params.require(:property).permit(:title, :description, :address, :bedrooms, :bathrooms, :family_rooms, :reception_rooms, :latitude, :longitude, :features, :agent_id, :agent_name, :date_available, :building_name, :district, :indoor_size, :saleable_area, :buy, :rent, :refid, :building_age, :outdoor_size, :float, :inclusive_display, :inclusive_mfee, :inclusive_govr, :address_display, :street, :view, :layout, :floor, :uuid, :user_id, :data_source, :enabled,:tag_list, item_images_attributes: [:id, :_destroy], item_images: [])
    end
   
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/views/properties/_feedback.html.erb
<h1>非常感谢您的留言，稍后我们会为您提供专业的咨询服务。</h1>

app/views/properties/_form.html.erb
<%= form_for(@property) do |f| %>
  <% if @property.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@property.errors.count, "error") %> prohibited this property from being saved:</h2>

      <ul>
      <% @property.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :bedrooms %><br>
    <%= f.number_field :bedrooms %>
  </div>
  <div class="field">
    <%= f.label :bathrooms %><br>
    <%= f.number_field :bathrooms %>
  </div>
  <div class="field">
    <%= f.label :family_rooms %><br>
    <%= f.number_field :family_rooms %>
  </div>
  <div class="field">
    <%= f.label :reception_rooms %><br>
    <%= f.number_field :reception_rooms %>
  </div>
  <div class="field">
    <%= f.label :latitude %><br>
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br>
    <%= f.text_field :longitude %>
  </div>
  <div class="field">
    <%= f.label :features %><br>
    <%= f.text_area :features %>
  </div>
  <div class="field">
    <%= f.label :agent_id %><br>
    <%= f.text_field :agent_id %>
  </div>
  <div class="field">
    <%= f.label :agent_name %><br>
    <%= f.text_field :agent_name %>
  </div>
  <div class="field">
    <%= f.label :date_available %><br>
    <%= f.datetime_select :date_available %>
  </div>
  <div class="field">
    <%= f.label :building_name %><br>
    <%= f.text_field :building_name %>
  </div>
  <div class="field">
    <%= f.label :district %><br>
    <%= f.text_field :district %>
  </div>
  <div class="field">
    <%= f.label :indoor_size %><br>
    <%= f.text_field :indoor_size %>
  </div>
  <div class="field">
    <%= f.label :saleable_area %><br>
    <%= f.text_field :saleable_area %>
  </div>
  <div class="field">
    <%= f.label :buy %><br>
    <%= f.text_field :buy %>
  </div>
  <div class="field">
    <%= f.label :rent %><br>
    <%= f.text_field :rent %>
  </div>
  <div class="field">
    <%= f.label :refid %><br>
    <%= f.text_field :refid %>
  </div>
  <div class="field">
    <%= f.label :building_age %><br>
    <%= f.text_field :building_age %>
  </div>
  <div class="field">
    <%= f.label :outdoor_size %><br>
    <%= f.text_field :outdoor_size %>
  </div>
  <div class="field">
    <%= f.label :float %><br>
    <%= f.text_field :float %>
  </div>
  <div class="field">
    <%= f.label :inclusive_display %><br>
    <%= f.check_box :inclusive_display %>
  </div>
  <div class="field">
    <%= f.label :inclusive_mfee %><br>
    <%= f.text_field :inclusive_mfee %>
  </div>
  <div class="field">
    <%= f.label :inclusive_govr %><br>
    <%= f.text_field :inclusive_govr %>
  </div>
  <div class="field">
    <%= f.label :address_display %><br>
    <%= f.check_box :address_display %>
  </div>
  <div class="field">
    <%= f.label :street %><br>
    <%= f.text_field :street %>
  </div>
  <div class="field">
    <%= f.label :view %><br>
    <%= f.text_field :view %>
  </div>
  <div class="field">
    <%= f.label :layout %><br>
    <%= f.text_field :layout %>
  </div>
  <div class="field">
    <%= f.label :floor %><br>
    <%= f.text_field :floor %>
  </div>
  <div class="field">
    <%= f.label :uuid %><br>
    <%= f.text_field :uuid %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :data_source %><br>
    <%= f.text_field :data_source %>
  </div>
  <div class="field">
    <%= f.label :enabled %><br>
    <%= f.check_box :enabled %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/properties/edit.html.erb
<h1>Editing property</h1>

<%= render 'form' %>

<%= link_to 'Show', @property %> |
<%= link_to 'Back', properties_path %>

app/views/properties/index.html.erb
<%=render 'public/header1'%>   

<!--导航部分-->
   <div class="tabs">
            <ul>
              <li>
                  <h1>热门房产</h1>
              </li>
            </ul> 
    </div>  

    <div class="clear"> </div>

<!--主体部分-->
  
  <div id="house">
    <div class="containers">
      <ul>
        <li>
            <div class="box">
              <a href="../house/william.html" target="_blank" >
                  <img class="show" src="http://jshouse.oss-cn-hangzhou.aliyuncs.com/images/william/image1.png"/>
                
                  <a class="price">The William'Melbourne,VIC 墨尔本</a>
                  <a class="price1">待定</a>
                  <a class="price2"></a>
                  </a>            
            </div>
          </li>
          <li>
            <div class="box">
              <a href="../house/newstead.html" target="_blank" >
                  <img class="show" src="http://jshouse.oss-cn-hangzhou.aliyuncs.com/images/newstead/image1.png"/>
                
                  <a class="price">NEWSTEAD TOWERS 布里斯班</a>
                  <a class="price1">待定</a>
                  <a class="price2"></a>
                  </a>            
            </div>
          </li>
          <li>
            <div class="box">
              <a href="../house/hub" target="_blank" >
                  <img class="show" src="http://jshouse.oss-cn-hangzhou.aliyuncs.com/images/hub/image1.png"/>
                
                  <a class="price"> “The Hub”, Richmond, VIC 墨尔本</a>
                  <a class="price1">待定</a>
                  <a class="price2"></a>
                  </a>            
            </div>
          </li>
          <li>
            <div class="box">
              <a href="../house/bromley.html" target="_blank" >
                  <img class="show" src="http://jshouse.oss-cn-hangzhou.aliyuncs.com/images/bromley/image3.png"/>
                
                  <a class="price"> STMARKS SQ 伦敦</a>
                  <a class="price1">待定</a>
                  <a class="price2"></a>
                  </a>            
            </div>
          </li>

          <% @properties.each do |property| %>
          <li>
            <div class="box">
              <a href="<%=property_path(property)%>" target="_blank" >
                  <img class="show" src="<%=property.item_images.first.image_url%>"/>
                
                  <a class="price"><%= property.building_name+","+property.address%></a>
                  <a class="price1"><%="$"+property.buy.to_i.to_s%></a>
                  <a class="price2"></a>
                  </a>            
            </div>
          </li>
          <% end %>     
        </ul>       
       </div>
      </div>

  </div>
<div class="clear"> </div>


<%=render 'public/footer'%>
<a id="back-to-top"></a>

app/views/properties/new.html.erb
<h1>New property</h1>

<%= render 'form' %>

<%= link_to 'Back', properties_path %>

app/views/properties/show.html.erb
<%=render 'public/header'%>
<!--导航部分-->
<div id="tabs">
	<ul>
		<li>
			<a href="#">
				<h1><%= @property.city %></h1>
			</a>

		</li>
	</ul>
</div>

<div class="clear"></div>
<div id="bd">
  <div class="containers">
    <div class="core">

      <div class="abstract">
        <h1>
         <div id="buliding_name"> <%=@property.building_name%></div>
          <button id="translate1" class="translate1" onclick="translate1();">点击翻译</button>
          <button id="translate2" class="translate2" onclick="translate2();">translate</button>
        </h1>

        <div>
          <ul>
            
            <li>
              <%="位置:"%>
              <span id="position" class="position"><%= @property.address %></span>
              <a class="chack" href="#pro-invest"><%= "查看地图"%></a>
            </li>
            <li>
              <%= "价格:"%>
              <span class="kind"><%="$"+@property.buy.to_i.to_s%></span>
            </li>
          </ul>
        </div>
      </div>

    <div class="clear"> </div>
      <div class="gallery">
        <div id="slider" class="nivoSlider">
        <% @property.item_images.each do |item_image| %>
         <img src="<%= item_image.image_url%>"/>
         <% end%>
        </div>
      </div>
      <div class="clear"> </div>

      <div id="fix" class="fix2">
        <div class="flat-content-navbar">
          <ul>
            <li>
              <a id="tab1" class="tab-item1" data-scoll="#pro-introduce" href="#pro-introduce" data-anchor="#pro-introduce" gaevent="#">项目介绍</a>
            </li>
            <li>
              <a id="tab2" class="tab-item2" data-scorll="#pro-data" href="#pro-data" data-anchor="pro-data" gaevent="#">
                项目特色
              </a>
            </li>
            <li>
                <a id="tab3" class="tab-item2" data-scroll="#pro-invest" href="#pro-invest" data-anchor="#pro-invest
                " gaevent="#">
                项目数据
                </a>
            </li>
              <li>
                <a id="tab4" class="tab-item2" data-scroll="#pro-map" href="#pro-map" data-anchor="#pro-map
                " gaevent="#">
                项目位置
                </a>
            </li>
          </ul>
        </div>
      </div>

      <div id="deal-stuff">
        <div class="introduce" id="pro-introduce">
          <h1>项目介绍</h1>
          <p id="description"><%=@property.description.html_safe%></p>
        </div>

        <div class="introduce" id="pro-data">
          <h1>项目特色</h1>
             <p class="description" id="feature"><%= @property.features.html_safe%></p>
        </div>

        <div class="introduce" id="pro-invest">
          <h1>项目数据</h1>
          <ul>
            <li><%="Bedroom:"%><span class="kind"><%=@property.bedrooms%></span></li>
            <li><%="Bathroom:"%><span class="kind"><%=@property.bathrooms%></span></li>
            <li><%="Reception room:"%><span class="kind"><%=@property.reception_rooms%></span></li>
            <li><%="Building age:"%><span class="kind"><%=@property.building_age%></span></li>
            <li><%="Indoor size:"%><span class="kind"><%=@property.indoor_size%></span></li>          
            <li><%="Outdoor size:"%><span class="kind"><%=@property.outdoor_size%></span></li>
            <li><%="Layout:"%><span class="kind"><%=@property.layout%></span></li>
            <li><%="floor:"%><span class="kind"><%=@property.floor%></span></li>
          </ul>

        </div>


        <div class="map" id="pro-map">
          <h1>项目位置</h1> 
          <div class="google" id="google">
            <iframe width="640" height="500" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="http://ditu.google.cn/maps?f=q&amp;source=s_q&amp;hl=zh-CN&amp;geocode=&amp;q=<%=@property.building_name%>&amp;sll=<%=@property.latitude%>,<%=@property.longitude%>&amp;sspn=<%=@property.latitude%>,<%=@property.longitude%>&amp;brcurrent=3,0x0:0x0,0%3B5,0,0&amp;ie=UTF8&amp;hq=&amp;ll=<%=@property.latitude%>,<%=@property.longitude%>&amp;spn=<%=@property.latitude%>,<%=@property.longitude%>&amp;t=m&amp;z=11&amp;output=embed"></iframe><br /><small><a href="http://ditu.google.cn/maps?f=q&amp;source=embed&amp;hl=zh-CN&amp;geocode=&amp;q=<%=@property.building_name%>&amp;sll=<%=@property.latitude%>,<%=@property.longitude%>&amp;sspn=<%=@property.latitude%>,<%=@property.longitude%>&amp;brcurrent=3,0x0:0x0,0%3B5,0,0&amp;ie=UTF8&amp;hq=&amp;ll=<%=@property.latitude%>,<%=@property.longitude%>&amp;spn=<%=@property.latitude%>,<%=@property.longitude%>&amp;t=m&amp;z=11" style="color:#0000FF;text-align:left">大图</a></small>
               
          </div>
        </div>
      </div>
    </div>



    <div class="feedback">
      <div class="information">
        <h3>感兴趣</h3>
        <div id="feedback" class="wrap">
          <%= form_for(@feedback,remote:true ) do |f| %>
            <div class="field">
              <%= f.label "姓名" %><br>
              <%= f.text_field :name %>
            </div>
            <div class="field">
              <%= f.label "电话" %><br>
              <%= f.telephone_field :phone %>
            </div>
            <div class="field">
              <%= f.label "电子邮件" %><br>
              <%= f.text_field :email %>
            </div>
            <div class="field">
              <%= f.label "留言" %><br>
              <%= f.text_area :message %>
            </div>
            <div class="actions">
              <%=f.submit "提交"%>
            </div>
          <% end %>
        </div>

      </div>
    </div>
  </div>
</div>
<div class="clear"></div>


<%=render 'public/footer'%>

<a id="back-to-top"></a>
<script>
function translate1(){

      document.getElementById("buliding_name").innerHTML="<%=@building_name1%>";
      document.getElementById("description").innerHTML="<small>通过百度翻译，不准之处请客官谅解</small> <br><br><br><%=@description1%>";
      document.getElementById("translate1").style.display="none";
      document.getElementById("translate2").style.display="block";
}


function translate2(){
        document.getElementById("buliding_name").innerHTML="<%=@property.building_name%>";
      document.getElementById("description").innerHTML="<%=@property.description.html_safe %>";
      document.getElementById("translate1").style.display="block";
      document.getElementById("translate2").style.display="none";
      
}
</script>