config/routes.rb
Rails.application.routes.draw do
  root 'properties#index'
  
  get 'welcome/index'
  resources :addresses do
    resources :properties 
  end

  
  resources :properties do
      resources :item_images
      resources :feedbacks
    end
    
    

  get 'admin/index'
  controller :sessions do
    get 'login'=>:new
    post 'login'=>:create
    delete 'logout'=>:destroy
  end

  get 'sessions/create'

  get 'sessions/destroy'

  resources :users
  resources :feedbacks

   namespace :api, path: '/api/1.0', format: 'json' do

       resources :properties
  end
  

  

end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
  skip_before_action :authorize
  before_action :set_address, only: [:show, :edit, :update, :destroy]

  # GET /addresses
  # GET /addresses.json


  def index
    @addresses = Address.all
    @australia=Address.where(country: 'Australia')
    @england=Address.where(country: 'England')
  end

  # GET /addresses/1
  # GET /addresses/1.json
  def show
  @city=@address.city
  @properties=Property.where(city: @city,enabled: "1")
  end

  # GET /addresses/new
  def new
    @address = Address.new
  end

  # GET /addresses/1/edit
  def edit
  end

  # POST /addresses
  # POST /addresses.json
  def create
    @address = Address.new(address_params)
    puts address_params
    respond_to do |format|
      if @address.save
        format.html { redirect_to @address, notice: 'Address was successfully created.' }
        format.json { render :show, status: :created, location: @address }
      else
        format.html { render :new }
        format.json { render json: @address.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /addresses/1
  # PATCH/PUT /addresses/1.json
  def update
    respond_to do |format|
      if @address.update(address_params)
        format.html { redirect_to @address, notice: 'Address was successfully updated.' }
        format.json { render :show, status: :ok, location: @address }
      else
        format.html { render :edit }
        format.json { render json: @address.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /addresses/1
  # DELETE /addresses/1.json
  def destroy
    @address.destroy
    respond_to do |format|
      format.html { redirect_to addresses_url, notice: 'Address was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_address
      @address = Address.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def address_params
      params.require(:address).permit(:country, :city, :city_img)
    end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/views/addresses/_form.html.erb
<%= form_for(@address) do |f| %>
  <% if @address.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@address.errors.count, "error") %> prohibited this address from being saved:</h2>

      <ul>
      <% @address.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :country %><br>
    <%= f.text_field :country %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :city_img %><br>
    <%= f.text_field :city_img %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/addresses/edit.html.erb
<h1>Editing address</h1>

<%= render 'form' %>

<%= link_to 'Show', @address %> |
<%= link_to 'Back', addresses_path %>

app/views/addresses/index.html.erb
<%=render 'public/header'%>
  
   <div class="clear"> </div> 


<div id="city">
  <div class="containers">
    <div class="tabs">
            <ul>
              <li>
                  <h1>澳大利亚</h1>                
              </li>
            </ul> 
    </div> 
    <ul>
        <% @australia.each do |c| %>
          <li class="cc">
            <div class="hot">
                <a href="<%=address_path(c)%>">
                  <img src="<%=c.city_img%>"/>
                </a>
              <a class="price">
                <%=c.city%>
                </a>
            </div>
          </li>
        <% end %>
    </ul>
    <div class="clear"></div> 
    
    <div class="tabs">
            <ul>
              <li>
                <a href="./listpage.html">
                  <h1>英国</h1>
                </a>
              </li>
            </ul> 
    </div> 
    <ul>
        <% @england.each do |c| %>
          <li>
            <div class="hot">
                        <a href="<%=address_path(c)%>">
                  <img src="<%=c.city_img%>"/>
                </a>
              <a class="price">
                <%=c.city%>
                </a>
            </div>
          </li>
          <% end %>
    </ul>

      
  </div>
</div>



<%=render 'public/footer'%>

<a id="back-to-top"></a>

app/views/addresses/new.html.erb
<h1>New address</h1>

<%= render 'form' %>

<%= link_to 'Back', addresses_path %>

app/views/addresses/show.html.erb
<!--头部-->
	<%=render 'public/header'%>
	
   <div class="clear"> </div>     

<!--导航部分-->
   <div class="tabs">
            <ul>
            	<li>
            	    <h1><%=@address.city%></h1>
            	</li>
            </ul> 
    </div>  

    <div class="clear"> </div>

<!--主体部分-->
	
	<div id="house">
		<div class="containers">
			
         
		    <ul>
		    	<% @properties.each do  |property|%>
		    	<li>
		    		<div class="hot">
                        <a href="<%=property_path(property)%>" target="_blank">
		    			    <img src="<%=property.item_images.first.image_url%>"/>
		    		    </a>
		    		    <div class="abstract">
		    			    <a href="<%=property_path(property)%>">
		    			        <h1><%=property.building_name%></h1>
		    			    </a>		    			    
		    			    <p>Style：卧<%= property.bathrooms%>卫<%= property.reception_rooms%>厅</p>
		    			    <p>Address：<%= property.address %></p>
		    			    <p>Price：
		    				   <b class="number"><%= property.buy %></b>
		    			    </p>
		    		    </div>
		    		</div>
		    	</li>
		    	<% end %>
		    </ul>
		    

	    </div>

	</div>


<div class="clear"> </div>

<%=render 'public/footer'%>
 	<a id="back-to-top"></a>