config/routes.rb
Rails.application.routes.draw do
  root 'properties#index'
  
  get 'welcome/index'
  resources :addresses do
    resources :properties 
  end

  
  resources :properties do
      resources :item_images
      resources :feedbacks
    end
    
    

  get 'admin/index'
  controller :sessions do
    get 'login'=>:new
    post 'login'=>:create
    delete 'logout'=>:destroy
  end

  get 'sessions/create'

  get 'sessions/destroy'

  resources :users
  resources :feedbacks

   namespace :api, path: '/api/1.0', format: 'json' do

       resources :properties
  end
  

  

end

app/models/feedback.rb
class Feedback < ActiveRecord::Base
	validates :name,:phone,:email, presence:true
end

app/controllers/feedbacks_controller.rb
class FeedbacksController < ApplicationController
 skip_before_action :authorize, only:[:new ,:show,:edit,:create,:update,:destroy]
  before_action :set_feedback, only: [:show, :edit, :update, :destroy]

  # GET /feedbacks
  # GET /feedbacks.json
  def index
    @feedbacks = Feedback.all 
  end

  # GET /feedbacks/1
  # GET /feedbacks/1.json
  def show
  end

  # GET /feedbacks/new
  def new
    @feedback = Feedback.new
  end

  # GET /feedbacks/1/edit
  def edit
  end

  # POST /feedbacks
  # POST /feedbacks.json
  def create
    
    @feedback = Feedback.create(feedback_params)
    respond_to do |format|
      if @feedback.save
        FeedbackNotifier.new_feedback(@feedback).deliver 
        format.html { redirect_to @feedback }
        format.js
        format.json { render :show, status: :created, location: @feedback }
      else
        format.html { redirect_to property_path(@property) }
        format.js { render action: 'create_fail' }
      end
    end
  end

  # PATCH/PUT /feedbacks/1
  # PATCH/PUT /feedbacks/1.json
  def update
    respond_to do |format|
      if @feedback.update(feedback_params)
        if @feedback.reply.present?
          FeedbackNotifier.reply_feedback(@feedback).deliver
        end
        format.html { redirect_to feedbacks_url, notice: 'Feedback was successfully updated.' }
        format.json { render :show, status: :ok, location: @feedback }
      else
        format.html { render :edit }
        format.json { render json: @feedback.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /feedbacks/1
  # DELETE /feedbacks/1.json
  def destroy
    @feedback.destroy
    respond_to do |format|
      format.html { redirect_to feedbacks_url, notice: 'Feedback was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_feedback
      @feedback = Feedback.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def feedback_params
      params.require(:feedback).permit(:name, :phone, :email, :reply ,:message,:property_id)
    end
end

app/helpers/feedbacks_helper.rb
module FeedbacksHelper
end

app/views/feedbacks/_feedback.html.erb
<h1>非常感谢您的留言，稍后我们会为您提供专业的咨询服务。</h1>

app/views/feedbacks/_form.html.erb
<%= form_for(@feedback) do |f| %>
  <% if @feedback.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@feedback.errors.count, "error") %> prohibited this feedback from being saved:</h2>

      <ul>
      <% @feedback.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label "姓名" %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label "手机号" %><br>
    <%= f.telephone_field :phone %>
  </div>
  <div class="field">
    <%= f.label "电子邮箱" %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label "留言" %><br>
    <%= f.text_area :message %>
  </div>
  <div class="actions">
    <%= f.submit "提交" %>
  </div>
<% end %>

app/views/feedbacks/_form1.html.erb
   <div class="field">
    <%= "姓名："+@feedback.name %>
  </div>
  <div class="field">
    <%= "电话："+@feedback.phone %>
  </div>
  <div class="field">
    <%="电子邮件：" +@feedback.email %>
  </div>
  <div class="field">

    <%= "留言："+@feedback.message %>
  </div>

<%= form_for(@feedback) do |f| %>
  <% if @feedback.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@feedback.errors.count, "error") %> prohibited this feedback from being saved:</h2>

      <ul>
      <% @feedback.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %> 
<div class="field">
    <%= f.label "回复：" %><br>
    <%= f.text_field :message %>
  </div>
  <div class="actions">
    <%= f.submit "提交" %>
  </div>
<% end %>

app/views/feedbacks/create.js.erb
$('#feedback').html(" <%= escape_javascript(render(@feedback))%> ");

app/views/feedbacks/create_fail.js.erb
alert("请填全表单！")

app/views/feedbacks/edit.html.erb
<%= render 'form1' %>

app/views/feedbacks/index.html.erb
<table>
  <thead>
    <tr>
       <th>房产编号</th>
      <th>姓名</th>
      <th>电话号码</th>
      <th>电子邮件</th>
      <th>消息</th>
      <th class="note1">备注</th>
      <th>状态</th>
      <th>经理</th>
      <th colspan="3">操作</th>
    </tr>
  </thead>

  <tbody>
    <% @feedbacks.each do |feedback| %>
      <tr class="<%= cycle('list_line_odd', 'list_line_even') %>">
        <td><%= feedback.property_id %></td>
        <td><%= feedback.name %></td>
        <td><%= feedback.phone %></td>
        <td><%= feedback.email %></td>
        <td ><%= feedback.message %></td>
         <td><%= feedback.reply %></td>
        <td class="note2"><%= feedback.note %></td>
        <td><%= feedback.status %></td>
        <td><%= feedback.manager %></td>

        <td class="list_action1">
        <%= link_to '编辑', edit_feedback_path(feedback) %><td/>
        <td class="list_action2"><%= link_to '删除', feedback, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/feedbacks/new.html.erb
<%= render 'form' %>

app/views/feedbacks/show.html.erb
<p id="notice"><%= notice %></p>
<p style="font-size:13px;">感谢您的意见反馈，我们会及时联系您！</p>
 